[project]
name = "keylol-tg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "climage>=0.2.2",
    "httpx>=0.28.1",
    "lxml>=5.4.0",
    "pyrofork>=2.3.67",
    "python-dotenv>=1.1.1",
    "schedule>=1.2.2",
    "tgcrypto>=1.2.5",
]
